### ISSUE TITLE
Offering Assistance

### ISSUE THREAD

**Issue by cedricbahirwe** [apps-fab/exercism-app#40]
Dear @angiemugo, @savekirk 

I hope this message finds you well. I recently came across this repo and was intrigued by the work you're doing.
I, myself, am a big fan of [Exercism](https://exercism.org/tracks/swift), and I wanted to check if someone was already working on a client and that's how I found this project on GitHub.
The project seems exciting and aligns with my interests and expertise.
Having experience in iOS Development and Apple Ecosystems, I am eager to offer my assistance to the project.

Please let me know if there are any specific areas where you currently need a hand. I would be more than willing to discuss how I can best contribute to the project's success.

Looking forward to the possibility of working together and contributing to the growth of your project.

**Comment by angiemugo** [comment]
Hi Cedric, 
It's so great to hear from you. Yes, we would definitely appreciate the help. I am in the middle of a refactor. As you can see the way the "VM" interacts with the view is a little convoluted and I have been researching ways to make it better. I am going off of this piece([https://developer.apple.com/forums/thread/699003](https://calendly.com/mugoangela)) I found on the apple forums. I will be raising a PR on this soon and I think it's a good starting point for us to discuss your thoughts and how you could help us. We are open to discussing it when you have a chance. You can book a time in my [calendar](https://calendly.com/mugoangela) or send me available time slots for the same on your end.

**Comment by cedricbahirwe** [comment]
Great to hear from you!
I attempted to book a time on your calendar using Calendly, but it seems
that the calendar is currently unavailable. Could you please share a valid
link to your calendar?

**Comment by angiemugo** [comment]
Hi @cedricbahirwe, sorry about that. I have slots from next week Monday at 12 noon onwards. Please let me know what time works

**Comment by cedricbahirwe** [comment]
Noon sounds great

**Comment by cedricbahirwe** [comment]
> Please share your email so that I set up a meeting

[cedricaganzebahirwe@gmail.com](mailto:cedricaganzebahirwe@gmail.com)

**Comment by angiemugo** [comment]
@cedricbahirwe just saw I have a conflicting meeting at 12 so I have scheduled from 1.

**Comment by cedricbahirwe** [comment]
Okay
