### ISSUE TITLE
List of some things I found

### ISSUE THREAD

**Issue by cedricbahirwe** [apps-fab/exercism-app#45]
I cloned and tried to run this project as a novice, here are some issues:

## Project Configuration
- [x]  When trying to run after cloning: 
`No Account for Team "S82GZQ59NS". (The workaround was to set the dev team to my own)`
<img width="767" alt="Screenshot 2023-10-26 at 11 25 15" src="https://github.com/apps-fab/exercism-app/assets/49038614/94eafcc7-316a-4f1d-8fd3-2efed5c6163a">

- [x] Missing a `Getting Started Guide` on how to build and run the project
- [x] Documenting the swift packages used and why they are used(needed) in this project

## Login View

- [x] Text Missing when in Light Mode

<img width="462" alt="Screenshot 2023-10-26 at 11 35 09" src="https://github.com/apps-fab/exercism-app/assets/49038614/56c67ac4-6b7d-48b9-bb45-f837747c7229">

**Comment by angiemugo** [comment]
hi @cedricbahirwe, thanks for these. 
They all look like good first issues to me. Would you like to tackle them? 
The first 3 are documentation tasks so maybe you could look into those?

**Comment by cedricbahirwe** [comment]
Yeah, of course, Thinking of creating different md files instead of putting everything in README.md file
What do you think?

**Comment by angiemugo** [comment]
I think for now I would recommend just one md file. I don't believe our project is big enough to require more than one .md

**Comment by angiemugo** [comment]
@cedricbahirwe I think the text missing in light mode would be a fun task to look into meanwhile?

**Comment by cedricbahirwe** [comment]
Sounds good
