### ISSUE TITLE
Syntax Missing on less ubiquitous languages 

### ISSUE THREAD

**Issue by angiemugo** [apps-fab/exercism-app#61]
- Syntax is missing in some languages like `Gleam` 
- SInce we are using this [code editor](https://github.com/ZeeZide/CodeEditor) that builds on top of [this syntax highlighter](https://github.com/raspu/Highlightr), some languages are not handled yet. 
- Exercism uses the same highlighter, however they handle those languages a little differently 
-  [This](https://github.com/exercism/website/blob/0c6a7a46f2252def0ad4aebc02dd9b51bf964a1c/app/javascript/declarations/index.d.ts#L85) is how they handle gleam.

**Comment by angiemugo** [comment]
Update: stuck on this because of some knowledge gaps(Javascript-wise 😅) working on it though. Hoping to have something next week.

**Comment by cedricbahirwe** [comment]
> Update: stuck on this because of some knowledge gaps(Javascript-wise 😅) working on it though. Hoping to have something next week.

Thanks for the update, @angiemugo! Let me know if you need help with anything else...

**Comment by angiemugo** [comment]
Aside from JavaScript(node) or including?

**Comment by cedricbahirwe** [comment]
> Aside from JavaScript(node) or including? 😅

eehh... Including?.. I guess...🤷🏽‍♂️Two stuck heads are better than one 🤭🤭

**Comment by cedricbahirwe** [comment]
Hey @angiemugo ,

### Findings Summary:

1. The `Highlightr` Swift package we're using isn't maintained anymore. Forking it and adding missing pieces seems like the best approach.
2. `Exercism` handles `Gleam` as a [self-hosted](https://github.com/exercism/website/blob/0c6a7a46f2252def0ad4aebc02dd9b51bf964a1c/app/javascript/declarations/index.d.ts#L85) language. We should extract the [JavaScript file](https://github.com/gleam-lang/gleam-highlight.js) defining Gleam and integrate it into our `Highlightr` package.
3. The CSS styles in `Highlightr` are outdated. Updating them based on the latest `highlight.js` repository is necessary.
4. To handle new languages, manually adding their definition JavaScript files directly to the project and utilizing our existing mechanism for language registration is recommended.
5. We also need to update our `highlight.min.js` file to mirror the [lastest](https://github.com/highlightjs/highlight.js) one

Hope this helps!

---

**Comment by angiemugo** [comment]
> Hey @angiemugo ,
> 
> ### Findings Summary:
> 1. The `Highlightr` Swift package we're using isn't maintained anymore. Forking it and adding missing pieces seems like the best approach.
> 2. `Exercism` handles `Gleam` as a [self-hosted](https://github.com/exercism/website/blob/0c6a7a46f2252def0ad4aebc02dd9b51bf964a1c/app/javascript/declarations/index.d.ts#L85) language. We should extract the [JavaScript file](https://github.com/gleam-lang/gleam-highlight.js) defining Gleam and integrate it into our `Highlightr` package.
> 3. The CSS styles in `Highlightr` are outdated. Updating them based on the latest `highlight.js` repository is necessary.
> 4. To handle new languages, manually adding their definition JavaScript files directly to the project and utilizing our existing mechanism for language registration is recommended.
> 5. We also need to update our `highlight.min.js` file to mirror the [lastest](https://github.com/highlightjs/highlight.js) one
> 
> Hope this helps!

great job @cedricbahirwe.

**Comment by angiemugo** [comment]
Missing languages

- [ ] Ballerina
- [ ] Abap
- [ ] Gleam
- [ ] Cobol
- [ ] Unison
- [ ] x-86 assembly 
- [ ] Zig
- [ ] wren
- [ ] visual Basic
- [ ] V
- [ ] Standard Ml 
- [ ] SQlite 
- [ ] Red
- [ ] Raku
- [ ] Racket
- [ ] PureScript
- [ ] Pharo
- [ ] LFE
- [ ] jq
- [ ] euphoria
- [ ] 8th

**Comment by angiemugo** [comment]
It seems some languages are not handled by Highlightjs at all. Those are handled using codeMirror. 🤕. I'll explore that path and see where it leads us

**Comment by angiemugo** [comment]
Found a `highlightAll` hack that fixes this.

**Comment by angiemugo** [comment]
- During my escapades to update Highlightr, I discovered a simplification: there's no need to individually add the minified files to Highlightr. 
- Instead, I incorporated them into my local Highlight.js, and they were automatically included when I generated a minified file using `tools/build.js`. 
-  However, a lingering issue persists: when the language provided to `Highlight()` isn't recognized, it returns `undefined` rather than `nil`, as expected in Swift. 
- Consequently, languages without Highlight.js extensions remain unhandled. 
- The objective now is to address this by conditionally handling such cases using `highlightAuto`.
- I have squashed all the earlier commits in favor of the new work on the commit `c4b3d0e` and later

**Comment by angiemugo** [comment]
We have a PR [here](https://github.com/raspu/Highlightr/pull/105)

**Comment by angiemugo** [comment]
The PR has been merged! However, I'll continue using the forked version since I added a small feature [here](https://github.com/apps-fab/Highlightr/commit/be58fdf4a41af1571c7b64259815bc770a98a0d6). For languages not recognized by Highlight.js, we default to `HighlightAuto`.

**Comment by savekirk** [comment]
> The PR has been merged! However, I'll continue using the forked version since I added a small feature [here](https://github.com/apps-fab/Highlightr/commit/be58fdf4a41af1571c7b64259815bc770a98a0d6). For languages not recognized by Highlight.js, we default to `HighlightAuto`. This issue has been fixed in this [PR](https://github.com/apps-fab/exercism-app/pull/67)

Great job on that 🎉 🚀
