### ISSUE TITLE
Issue with our .purple color usage

### ISSUE THREAD

**Issue by cedricbahirwe** [apps-fab/exercism-app#63]
Due to the introduction of `GeneratedAssetSymbols` in Xcode, we're encountering an issue with our purple color conflicting with the SwiftUI version. To address this, we must refine our naming and usage of the `.purple` color, perhaps opting for descriptors like `appAccent`, `appPurple`, or `mainPurple`.

![Screenshot 2024-05-08 at 20 57 52](https://github.com/apps-fab/exercism-app/assets/49038614/8d8e82be-380d-475a-be6d-bd32446eb199)

**Comment by angiemugo** [comment]
[Here](https://www.hackingwithswift.com/forums/swiftui/generatedassetsymbols-swift/23964) is an explanation for why this is a problem now
